baseURL = "https://dogancan.org"
languageCode = "en-us"
title = "Dogancan Ozturan"
theme = "cactus"
copyright = "Dogancan Ozturan" # cactus will use title if copyright is not set
disqusShortname = "dogancan" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"

summaryLength = 1

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "classic" # dark, light, white, or classic
  rss = false # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  description = "Hello! My name is Dogancan. I finished my PhD in Biomedical Sciences at [Koç University](https://www.ku.edu.tr). Currently, I am a postdoctoral research fellow at the [University of British Columbia](https://ubc.ca) in the [de Boer laboratory](https://deboer.bme.ubc.ca). My primary research focus is on gene regulation. For more details, please take a look at my [publications](https://scholar.google.com/citations?user=XkJXsgkAAAAJ&hl=en&inst=17001591832933267808)."
  mainSection = "posts" # your main section
  mainSectionTitle = " " # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 0 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "January 2006" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # only disqus, utterances, and cactus_comments is supported

  [[params.social]]
    name = "email"
    link = "dogancan (at) mail.ubc.ca"  # no need for "mailto:" in the head
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/dozturan"
  [[params.social]]
    name = "fa-bluesky"
    link = "https://bsky.app/profile/dogancan.org" 
  [[params.social]]
    name = "unsplash"
    link = "https://unsplash.com/dogancan"  
