baseURL = "https://dogancan.org"
languageCode = "en-us"
title = "Doğancan Özturan"
theme = "cactus"
copyright = "Doğancan Özturan" # cactus will use title if copyright is not set
disqusShortname = "dogancan" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"

summaryLength = 1

[[menu.main]]
name = "home"
url = "/"
weight = 1

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "classic" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = false # default

  # Home page settings
  description = "Hi! My name is Doğancan. I’ve received my PhD in biomedical sciences from [Koç University](https://www.ku.edu.tr) and currently working as a postdoctoral research fellow at [Vancouver Prostate Centre](https://www.prostatecentre.com/) in [University of British Columbia](https://ubc.ca). I’m working on transcription factor biology, mainly androgen receptor and its working mechanisms in transcription."
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = true # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "January 2006" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = true # default
    engine = "disqus" # only disqus, utterances, and cactus_comments is supported

  [[params.social]]
    name = "email"
    link = "dozturan at gmail dot com"  # no need for "mailto:" in the head
  [[params.social]]
    name = "scholar"
    link = "https://scholar.google.com/citations?user=XkJXsgkAAAAJ&hl=en&inst=17001591832933267808"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/dozturan"
  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/dogancan"  # no need for "mailto:" in the head
